name: Auto Assign
on: [push, pull_request]
jobs:
  add-reviewers-assignees:
    permissions: write-all
    name: Auto Add Reviewer and Assignees
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.6
        with:
          configuration-path: '.github/auto_assign.yml' # Only needed if you use something other than .github/auto_assign.yml