name: Auto Assign to Author

on:
  issues:
    types: [opened]

jobs:
  assign_to_author:
    runs-on: ubuntu-latest
    steps:
    - name: Assign issue to opener
      run: |
        ISSUE_NUMBER="${{ github.event.issue.number }}"
        AUTHOR="${{ github.event.issue.user.login }}"

        curl -s \
             -X POST \
             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/assignees" \
             -d "{\"assignees\":[\"${AUTHOR}\"]}"
